apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving-deployment
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
      - name: model-serving
        image: tensorflow/serving
        envFrom:
        - configMapRef:
            name: ${configmap}
        ports:
        - containerPort: 8501
        volumeMounts:
          - name: model-serving-volume
            mountPath: /models/half_plus_two
        resources:
          requests:
            memory: 32M
            cpu: 5m
          limits:
            memory: 64M
            cpu: 10m
      volumes:
        - name: model-serving-volume
          hostPath:
            path: /var/tmp/saved_model_half_plus_two_cpu
            type: Directory