apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving-deployment
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
      - name: model-serving
        image: model-serving:3.10.6
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64M
            cpu: 10m
          limits:
            memory: 128M
            cpu: 20m
