apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
  namespace: ${namespace}
  labels:
    app: model-serving
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
    protocol: TCP
    name: model-serving-http
  selector:
    app: model-serving